import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Webstore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="id">
      <head>
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body id="root" className={inter.className}>
        <div className="bg-slate-50 dark:bg-slate-900 dark:text-white text-black min-h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
